{"name": "test_create_authuser", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: Element: xpath->(//button[@type='button'])[10] not found in 5 seconds.", "trace": "self = <test_04_create_auth_user.TestCreateUser object at 0x0504A570>\n\n    @pytest.mark.flaky(reruns=3)\n    def test_create_authuser(self):\n    \n        login = Login(self.dr)\n        datas = datainfo.get_xls_to_dict(\"user.xlsx\", \"Sheet1\")[0]\n        data1s = datainfo.get_xls_to_dict(\"user.xlsx\", \"authuser\")[0]\n        aupg = authUserPage.AuthUsertPage(self.dr)\n        ta = userAction.UserAction(self.dr)\n        # t_data = datainfo.get_xls_to_dict(\"tenantdata.xlsx\",\"Sheet1\")[0]\n        login.login(datas[\"username\"], datas[\"password\"])\n>       ta.create_tenant_user(data1s[\"tenantname\"],data1s[\"username\"],data1s[\"firstname\"],data1s[\"password\"],data1s[\"repassword\"],data1s[\"email\"])\n\ntestcase\\test_04_create_auth_user.py:29: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\npublic\\appModel\\userAction.py:87: in create_tenant_user\n    self.a_u_pg.click_crate_user_button()\npublic\\pages\\authUserPage.py:19: in click_crate_user_button\n    self.dr.click(\"xpath->(//button[@type='button'])[10]\")\npublic\\common\\pyselenium.py:213: in click\n    self.element_wait(css)\npublic\\common\\pyselenium.py:91: in element_wait\n    WebDriverWait(self.driver, secs, 1).until(EC.presence_of_element_located((By.XPATH, value)), messages)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <selenium.webdriver.support.wait.WebDriverWait (session=\"ee320517-1624-46a6-9af7-bbc3fe42cfef\")>\nmethod = <selenium.webdriver.support.expected_conditions.presence_of_element_located object at 0x04985D10>\nmessage = \"Element: xpath->(//button[@type='button'])[10] not found in 5 seconds.\"\n\n    def until(self, method, message=''):\n        \"\"\"Calls the method provided with the driver as an argument until the \\\n        return value is not False.\"\"\"\n        screen = None\n        stacktrace = None\n    \n        end_time = time.time() + self._timeout\n        while True:\n            try:\n                value = method(self._driver)\n                if value:\n                    return value\n            except self._ignored_exceptions as exc:\n                screen = getattr(exc, 'screen', None)\n                stacktrace = getattr(exc, 'stacktrace', None)\n            time.sleep(self._poll)\n            if time.time() > end_time:\n                break\n>       raise TimeoutException(message, screen, stacktrace)\nE       selenium.common.exceptions.TimeoutException: Message: Element: xpath->(//button[@type='button'])[10] not found in 5 seconds.\n\nD:\\Env\\ui_auto\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py:80: TimeoutException"}, "attachments": [{"name": "log", "source": "e137798d-8d1c-49c0-ac99-9ff9955db83f-attachment.txt", "type": "text/plain"}], "start": 1572676332700, "stop": 1572676346568, "uuid": "144bb505-d86f-461c-8f5e-033b4b6b6304", "historyId": "30834f8e9ad851ca670cf429020d5829", "testCaseId": "5cb043ede1287fc0718c3028a218b5b6", "fullName": "testcase.test_04_create_auth_user.TestCreateUser#test_create_authuser", "labels": [{"name": "parentSuite", "value": "testcase"}, {"name": "suite", "value": "test_04_create_auth_user"}, {"name": "subSuite", "value": "TestCreateUser"}, {"name": "host", "value": "wuzs"}, {"name": "thread", "value": "7064-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.test_04_create_auth_user"}]}